// <auto-generated />
using System;
using Hsec.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hsec.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hsec.Domain.Entities.TObsISRegistroEncuestaMaestro", b =>
                {
                    b.Property<string>("CodObsIteracion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodigoTipo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodDescripcion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TObservacionIteraccionCorrelativo")
                        .HasColumnType("int");

                    b.HasKey("CodObsIteracion", "CodigoTipo", "CodDescripcion");

                    b.HasIndex("TObservacionIteraccionCorrelativo");

                    b.ToTable("TObsISRegistroEncuestaMaestros");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObsMaestro", b =>
                {
                    b.Property<int>("Correlativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodTabla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesTabla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Correlativo");

                    b.ToTable("TObsMaestros");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObsMiembrosEquipo", b =>
                {
                    b.Property<int>("Correlativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodObsIteracion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodPersonaMiembro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiderEquipo")
                        .HasColumnType("int");

                    b.Property<int?>("ObservacionIteraccionCorrelativo")
                        .HasColumnType("int");

                    b.HasKey("Correlativo");

                    b.HasIndex("ObservacionIteraccionCorrelativo");

                    b.ToTable("TObsMiembrosEquipos");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObsTaComentario", b =>
                {
                    b.Property<int>("Correlativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodTipoComentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroReferencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TareaCorrelativo")
                        .HasColumnType("int");

                    b.Property<int?>("TipoComentarioCorrelativo")
                        .HasColumnType("int");

                    b.HasKey("Correlativo");

                    b.HasIndex("TareaCorrelativo");

                    b.HasIndex("TipoComentarioCorrelativo");

                    b.ToTable("TObsTaComentarios");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObsTaEtapaTarea", b =>
                {
                    b.Property<int>("Correlativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionEtapaTarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TObservacionTarea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TareaCorrelativo")
                        .HasColumnType("int");

                    b.Property<string>("TituloEtapaTarea")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Correlativo");

                    b.HasIndex("TareaCorrelativo");

                    b.ToTable("TObsTaEtapaTareas");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObsTaRegistroEncuesta", b =>
                {
                    b.Property<string>("NroDocReferencia")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodTabla")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodPregunta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodRespuesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TareaCorrelativo")
                        .HasColumnType("int");

                    b.HasKey("NroDocReferencia", "CodTabla", "CodPregunta");

                    b.HasIndex("TareaCorrelativo");

                    b.ToTable("TObsTaRegistroEncuestas");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObservacion", b =>
                {
                    b.Property<int>("Correlativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodAreaHsec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodNivelRiesgo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodObservacion")
                        .HasColumnType("nvarchar(max)")
                        .IsUnicode(true);

                    b.Property<string>("CodObservadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodPosicionGer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodPosicionSup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodSubTipoObs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodSubUbicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodTabla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodTipoObservacion")
                        .HasColumnType("int");

                    b.Property<string>("CodUbicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodUbicacionEspecifica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesUbicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaObservacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoraObservacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Correlativo");

                    b.ToTable("TObservaciones");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObservacionComportamiento", b =>
                {
                    b.Property<int>("Correlativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CodActiRelacionada")
                        .HasColumnType("int");

                    b.Property<string>("CodActoSubEstandar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCorreccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodErrorObs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodHha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodObservacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodStopWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodTabla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompAccionInmediata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompObservada")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Correlativo");

                    b.ToTable("TObservacionComportamientos");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObservacionCondicion", b =>
                {
                    b.Property<int>("Correlativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CodActiRelacionada")
                        .HasColumnType("int");

                    b.Property<string>("CodCondicionSubEstandar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCorreccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodHha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodObservacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodStopWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodTabla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondAccionInmediata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondObservada")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Correlativo");

                    b.ToTable("TObservacionCondiciones");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObservacionIteraccion", b =>
                {
                    b.Property<int>("Correlativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccionesInmediatas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActividadTareaObs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodContratista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodLiderPersona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodObsIteracion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodObservacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodStopWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetalleComportamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipoInvolucrado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IteraccionSeguridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtroActividadRiesgo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtroComponente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StopWorkCorrelativo")
                        .HasColumnType("int");

                    b.HasKey("Correlativo");

                    b.HasIndex("StopWorkCorrelativo");

                    b.ToTable("TObservacionIteracciones");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObservacionTarea", b =>
                {
                    b.Property<int>("Correlativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CodActiRelacionada")
                        .HasColumnType("int");

                    b.Property<string>("CodErrorObs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodEstadoObs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodHha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodObservacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodStopWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodTabla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComenRecoOpor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesConclusiones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesConclusionesProModi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesConclusionesfeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TareaObservada")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Correlativo");

                    b.ToTable("TObservacionTareas");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObsISRegistroEncuestaMaestro", b =>
                {
                    b.HasOne("Hsec.Domain.Entities.TObservacionIteraccion", null)
                        .WithMany("TOISRegistroEncuestaMaestro")
                        .HasForeignKey("TObservacionIteraccionCorrelativo");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObsMiembrosEquipo", b =>
                {
                    b.HasOne("Hsec.Domain.Entities.TObservacionIteraccion", "ObservacionIteraccion")
                        .WithMany()
                        .HasForeignKey("ObservacionIteraccionCorrelativo");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObsTaComentario", b =>
                {
                    b.HasOne("Hsec.Domain.Entities.TObservacionTarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaCorrelativo");

                    b.HasOne("Hsec.Domain.Entities.TObsMaestro", "TipoComentario")
                        .WithMany()
                        .HasForeignKey("TipoComentarioCorrelativo");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObsTaEtapaTarea", b =>
                {
                    b.HasOne("Hsec.Domain.Entities.TObservacionTarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaCorrelativo");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObsTaRegistroEncuesta", b =>
                {
                    b.HasOne("Hsec.Domain.Entities.TObservacionTarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaCorrelativo");
                });

            modelBuilder.Entity("Hsec.Domain.Entities.TObservacionIteraccion", b =>
                {
                    b.HasOne("Hsec.Domain.Entities.TObsMaestro", "StopWork")
                        .WithMany()
                        .HasForeignKey("StopWorkCorrelativo");
                });
#pragma warning restore 612, 618
        }
    }
}
